### ISSUE TITLE
Update types to match latest version 12.0.1

### ISSUE THREAD

**Issue by laurensiusadi** [Jack-Works/matrix-js-sdk-type#1]
I'm trying to use this package, it seems it's not up to date.
Please update to match latest version 12.0.1.
Thanks.

**Comment by Jack-Works** [comment]
Upgraded to version 12.0.1. Please notice it added a dependency from https://gitlab.matrix.org/api/v4/projects/27/packages/npm/@matrix-org/olm/-/@matrix-org/olm-3.2.3.tgz

**Comment by laurensiusadi** [comment]
Thanks!

**Comment by laurensiusadi** [comment]
@Jack-Works 
Copying the code from readme:
```
import _matrix from "matrix-js-sdk";
const matrix: typeof import("matrix-js-sdk-type/dts/matrix.d") = _matrix;
```
How should I use `matrix` variable here?
How do I import `createClient`?
Is this right?
```
`import _matrix, { RoomMember, createClient, MatrixEvent } from "matrix-js-sdk";`
```
I'm really new to TS.

**Comment by Jack-Works** [comment]
Hi, the old installation guide is not friendly. I have updated the guide. Now please uninstall `matrix-js-sdk-type` and re-install by a command like `npm i https://github.com/Jack-Works/matrix-js-sdk-type/`, and it is ready to use like 

```js
import {createClient} from 'matrix-js-sdk'
```

**Comment by laurensiusadi** [comment]
Here's my imports:
```
import { createClient, MatrixClient, MatrixEvent, RoomMember } from "matrix-js-sdk";
import { WebStorageSessionStore } from "matrix-js-sdk/src/store/session/webstorage";
import { IndexedDBCryptoStore } from "matrix-js-sdk/src/crypto/store/indexeddb-crypto-store";
import Olm from "@matrix-org/olm/olm_legacy";
```

Besides `createClient` the rest imported from matrix is typings.
Is that correct or should I use typing from this repo?

Also, the rest `WebStorageSessionStore`, `IndexedDBCryptoStore`, and `Olm` still doesn't get typed.
VSCode says `Could not find a declaration file for module 'matrix-js-sdk/src/store/session/webstorage'`

Is there any more setup needed besides just installing this repo?

**Comment by Jack-Works** [comment]
Hmm, so you need to import from a subdirectory of the matrix-js-sdk? I didn't consider that.

**Comment by Jack-Works** [comment]
Isn't all APIs are exported in the `matrix-js-sdk`?

**Comment by laurensiusadi** [comment]
If I try to do this
```
import { WebStorageSessionStore } from "matrix-js-sdk"
```

I got errors: `Module '"matrix-js-sdk"' has no exported member 'WebStorageSessionStore'.`
I learned this setup from https://github.com/matrix-org/matrix-react-sdk/blob/199c80315e66f4151ea99328f8f3edf56cc6d6cb/src/utils/createMatrixClient.ts#L19

**Comment by Jack-Works** [comment]
Ok please try to upgrade to bdaa732b8584f3aff92007f9b2213125c84bfc2b, that might fix your problem. @laurensiusadi

**Comment by Jack-Works** [comment]
![image](https://user-images.githubusercontent.com/5390719/125418941-760d30f5-c256-44e9-b7aa-8bade877f72c.png)

made a simple try

**Comment by laurensiusadi** [comment]
Wonderfull! Thanks!
